language: Java
jdk:
- openjdk9
addons:
  sonarcloud:
    organization: ricksbrown
    token:
      secure: ju5Iqsi0rSLpk2x0cXXqCy75fKbwAi/ays4z6uAsh5Vfk6MLpwpV4yi2oIjb2+0GqfB2eFH/YX+jZo4XfAgqABI3hHoXTn7JSosN0uESznAf9cZ9jMyUA9UnAMmkYP7vMskROrNfGzTL0FBl29nr+agjPBPCah2Ln6bOhZ+9UQwHAGrOFAWKCGoh0lwrH/9PKMZC4YYFsKKO4XUhoPL4hWUzxT+UGLHywPNML1F8R4XTyGf8tuszI7Rt4M2+66Glzc0+8ZICFFYykTNwzwaxvNlIM52XV/CgpvHAtbplJO2J1vJDmbqRDrC0J7Wrug8orhqsfoDeibNRMUtDbc+pn6nMcyjXsGjlj6DFd/VyB035gJg8AjrU9ha098mtKSaPDacmQBy4VYZ5TWEZ0ZGuMp09i6gV9q5yI/KXVN7ty/cHHiwIyt/OFYOEKLtzh8WaYA5h6WNRvq1e3miUg5237qsWQIYXmSxwvNumP3Fj7wZp1DFtZV1I7M/RKFlbeSZ3eLWtves4Y7fq7mc85AAv6WKih063ooSgr0/wzkC/U3sihopc2dnVDSZAE4MGy+xEfbgIwOP1vF6yiF9Axs6hjCl6E8cIowXBGDEPHH7kDbtvr9FWztECaBE+eWlz6p9XjBmHA42xqHVUBnz5L0RQqJdbs0PQ/XwLf+sQJn1GUEY=
script:
- "./travis.sh"
